### ISSUE TITLE
Denied access to push commit

### ISSUE THREAD

**Issue by kaseyjcowley** [erikthedeveloper/todo-laravel-angularjs-homestead#9]
@erikthedeveloper 
I attempted to push some changes to the kickstarter/phpspec branch and received the following errors:

remote: Permission to erikthedeveloper/todo-laravel-angularjs-homestead.git denied to kchunterdeluxe.
fatal: unable to access 'https://github.com/erikthedeveloper/todo-laravel-angularjs-homestead/': The requested URL returned error: 403

Did you have to enable me to push up to the repo?

**Comment by erikthedeveloper** [comment]
Whoops.   SUWDC you're good.  On mine.....   Fork it... Push to yours... Submit pull request . Should have thought of that lol sorry

**Comment by erikthedeveloper** [comment]
Scratch that. Should work now ;)
